--- tests/test_task.py	2022-02-03 06:17:48.518803886 +0000
+++ tests/test_task_processedpatch_77aa1a3b5.py	2022-02-03 11:15:20.404999325 +0000
@@ -541,6 +541,8 @@ class TestTaskTemplate(unittest.TestCase
             task_tmpl.new_task('junk-data')
 
     def test_new_task_bad_args(self):
+        task_tmpl = TaskTemplate('my-task-holder')
+        task = task_tmpl.new_task('dummy-data', loop=self.loop)
         """
         Trying to create a new task with invalid arguments must raise a
         `TypeError` exception.
