--- tests/test_task.py	2022-02-03 06:17:48.518803886 +0000
+++ tests/test_task_processedpatch_f925b0d87.py	2022-02-03 11:31:35.018317587 +0000
@@ -532,6 +532,7 @@ class TestTaskTemplate(unittest.TestCase
         self.assertEqual(task.inputs, 'junk-data')
 
     def test_new_task_unknown(self):
+        task = asyncio.ensure_future(my_coro_task(None))
         """
         Trying to create a new task with an unknown name must raise a
         `UnknownTaskName` exception.
